// ============================================================
// FLOOR PLAN — the real M4 ground-floor drawing, live.
//
// Geometry comes from floors-data.js (FLOOR_M4_G), which is
// generated by tools/export_floor.py out of the university's own
// CAD export. Coordinates are METRES, y-down, already rotated so
// the building sits square to the screen.
//
// Occupancy comes from rooms-data.js (OCC / ROOM_NAMES / PROGRAMS /
// COURSE_TITLES), and the calendar (TERM, NO_CLASS, DAY_NAME) plus
// tmin / t12 / ymd come from timetable.js — same single source the
// rooms page uses, so the two can never disagree.
//
// The CAD has no room numbers in it. Which polygon is M4-0-019 is
// therefore a human call: "label rooms" turns the plan into the
// tool that records it, and prints a paste-ready ROOM_POLY block.
// ============================================================

const F = FLOOR_M4_G;

// ---------- occupancy (same merge rule as rooms.js) ----------

const SLOTS = (() => {
    const map = new Map();
    for (const [day, s, e, code, room, prog, group, kind] of OCC) {
        const key = [day, s, e, code, room].join("|");
        if (!map.has(key)) {
            map.set(key, { day, s, e, code, room, kind, from: tmin(s), to: tmin(e), who: [] });
        }
        map.get(key).who.push({ prog, group });
    }
    return [...map.values()].sort((a, b) => a.from - b.from);
})();

const KIND_LABEL = { lec: "Lecture", tut: "Tutorial", lab: "Lab", res: "Reserved" };

// Codes a room on THIS floor could legitimately be. M4 level 0 only —
// offering M3 or an upper floor here would just invite a wrong label.
const FLOOR_CODES = [...new Set(SLOTS.map(s => s.room))]
    .filter(c => c.startsWith("M4-0-")).sort();

function slotsFor(room, day) {
    return SLOTS.filter(x => x.room === room && x.day === day);
}

// ---------- room code <-> polygon mapping ----------
//
// Lives in localStorage while it is being built, so a half-finished
// pass survives a reload. Once it is done, "copy mapping" prints the
// block to paste into floors-data.js and it stops being provisional.

const MAP_KEY = "linkcs.plan.M4-0.map";
let ROOM_MAP = {};
try {
    ROOM_MAP = JSON.parse(localStorage.getItem(MAP_KEY) || "{}");
} catch (e) { ROOM_MAP = {}; }
if (typeof ROOM_POLY !== "undefined") ROOM_MAP = Object.assign({}, ROOM_POLY, ROOM_MAP);

function saveMap() {
    try { localStorage.setItem(MAP_KEY, JSON.stringify(ROOM_MAP)); } catch (e) { /* private mode */ }
}

const codeOf = i => ROOM_MAP[i] || null;

// ---------- day selection (mirrors rooms.js) ----------

let viewDay = null;

function defaultDay(now) {
    const today = ymd(now);
    const dow = now.getDay();
    if (dow >= 1 && dow <= 5 && !NO_CLASS[today] && today >= TERM.start && today <= TERM.end) return dow;
    for (let i = 1; i <= 8; i++) {
        const d = new Date(now); d.setDate(d.getDate() + i);
        if (d.getDay() >= 1 && d.getDay() <= 5 && !NO_CLASS[ymd(d)]) return d.getDay();
    }
    return 1;
}

// A room is only "busy now" if the day being viewed is actually today.
function liveNow() {
    const now = new Date();
    return { now, isToday: viewDay === defaultDay(now) && viewDay === now.getDay(),
             mins: now.getHours() * 60 + now.getMinutes() };
}

function stateOf(i) {
    const code = codeOf(i);
    if (code === "-") return "skip";          // marked corridor / service
    if (!code) return "none";
    const { isToday, mins } = liveNow();
    // "busy" only ever means busy RIGHT NOW. Looking at another day there is no
    // now to be busy in, so a mapped room just reads as mapped.
    if (!isToday) return "free";
    return slotsFor(code, viewDay).some(s => mins >= s.from && mins < s.to) ? "busy" : "free";
}

// ---------- svg ----------

const svg = document.getElementById("plan");
const NS = "http://www.w3.org/2000/svg";
const el = (n, a) => { const e = document.createElementNS(NS, n); for (const k in a) e.setAttribute(k, a[k]); return e; };

let cam, gRooms, gLabels;

function build() {
    svg.innerHTML = "";
    cam = el("g", { id: "cam" });
    svg.appendChild(cam);

    gRooms = el("g", {});
    cam.appendChild(gRooms);
    for (const r of F.rooms) {
        gRooms.appendChild(el("polygon", {
            points: r.p.map(q => q.join(",")).join(" "),
            class: "rm", "data-i": r.i
        }));
    }

    // drawing order: soft stuff under, walls and doors on top
    for (const k of ["glazing", "structure", "wall", "door"]) {
        if (F.layers[k]) cam.appendChild(el("path", { d: F.layers[k], class: "l-" + k }));
    }

    gLabels = el("g", {});
    cam.appendChild(gLabels);
    paint();
    fit();
}

function paint() {
    for (const p of gRooms.children) {
        const i = +p.dataset.i;
        p.setAttribute("class", "rm s-" + stateOf(i) + (i === selected ? " sel" : ""));
    }
    gLabels.innerHTML = "";
    for (const r of F.rooms) {
        const code = codeOf(r.i);
        const [cx, cy] = r.c;
        if (code && code !== "-") {
            // dy in em, so the two lines stay correctly spaced at any zoom
            const t = el("text", { x: cx, y: cy, class: "rlab" });
            t.appendChild(tspan(cx, "-0.15em", ROOM_NAMES[code] || code, null));
            t.appendChild(tspan(cx, "1.5em", code, "sub"));
            gLabels.appendChild(t);
        } else if (labelling) {
            const t = el("text", { x: cx, y: cy, class: "rnum", dy: "0.35em" });
            t.textContent = String(r.i);
            gLabels.appendChild(t);
        }
    }
}

function tspan(x, dy, s, cls) {
    const t = el("tspan", cls ? { x, dy, class: cls } : { x, dy });
    t.textContent = s;
    return t;
}

// ---------- pan / zoom ----------
//
// The camera IS the viewBox, in metres. Nothing here depends on the element's
// pixel size at build time, so a late reflow (web fonts landing, a resize, the
// side panel changing width) can never leave the drawing off-centre.

let view = { x: 0, y: 0, w: F.w, h: F.h };   // metres

const PAD = 1.5;                              // metres of breathing room at fit
const MIN_W = 3;                              // do not zoom past a ~3 m field of view

function applyView() {
    svg.setAttribute("viewBox", `${view.x} ${view.y} ${view.w} ${view.h}`);
    // px per metre, read live so it is always the real one
    const pxPerM = (svg.getBoundingClientRect().width || 900) / view.w;
    svg.style.setProperty("--kz", pxPerM);    // text divides by this to hold its size
    updateScaleBar(pxPerM);
}

function fit() {
    const r = svg.getBoundingClientRect();
    const aspect = (r.width || 900) / (r.height || 640);
    let w = F.w + PAD * 2, h = F.h + PAD * 2;
    // grow the short side so the whole floor is inside whatever shape the box is
    if (w / h < aspect) w = h * aspect; else h = w / aspect;
    view = { x: F.w / 2 - w / 2, y: F.h / 2 - h / 2, w, h };
    applyView();
}

function updateScaleBar(pxPerM) {
    const nice = [1, 2, 5, 10, 20, 50, 100];
    const m = nice.reduce((a, b) => Math.abs(b - 90 / pxPerM) < Math.abs(a - 90 / pxPerM) ? b : a);
    document.getElementById("scale-bar").style.width = (m * pxPerM) + "px";
    document.getElementById("scale-txt").textContent = m + " m";
}

// screen point -> metres, using the box as it is right now
function toM(ev) {
    const r = svg.getBoundingClientRect();
    return [view.x + (ev.clientX - r.left) / r.width * view.w,
            view.y + (ev.clientY - r.top) / r.height * view.h];
}

svg.addEventListener("wheel", ev => {
    ev.preventDefault();
    const [mx, my] = toM(ev);
    const f = Math.exp(ev.deltaY * 0.0016);
    const w = Math.max(MIN_W, Math.min((F.w + PAD * 2) * 2.5, view.w * f));
    const s = w / view.w;
    // keep the metre under the cursor pinned to the cursor
    view = { x: mx - (mx - view.x) * s, y: my - (my - view.y) * s, w, h: view.h * s };
    applyView();
}, { passive: false });

// A tap selects a room, a drag pans. Pointer capture is taken only once a real
// drag starts: capturing on pointerdown would make every click retarget to the
// <svg>, and the room under the finger would never see it.
let drag = null;
svg.addEventListener("pointerdown", ev => {
    const r = svg.getBoundingClientRect();
    drag = { x: ev.clientX, y: ev.clientY, vx: view.x, vy: view.y,
             mpp: view.w / r.width, id: ev.pointerId, moved: false };
});
svg.addEventListener("pointermove", ev => {
    if (!drag) return;
    const dx = ev.clientX - drag.x, dy = ev.clientY - drag.y;
    if (!drag.moved && Math.abs(dx) + Math.abs(dy) > 3) {
        drag.moved = true;
        svg.setPointerCapture(drag.id);
        svg.classList.add("dragging");
    }
    if (!drag.moved) return;
    view.x = drag.vx - dx * drag.mpp;
    view.y = drag.vy - dy * drag.mpp;
    applyView();
});
svg.addEventListener("pointerup", ev => {
    if (drag && !drag.moved) {
        // walls and door swings sit on top of the rooms, so take the first
        // room in the hit stack rather than whatever is literally on top
        const hit = document.elementsFromPoint(ev.clientX, ev.clientY)
            .find(e => e.classList && e.classList.contains("rm"));
        select(hit ? +hit.dataset.i : null);
    }
    if (drag && drag.moved) svg.releasePointerCapture(drag.id);
    drag = null;
    svg.classList.remove("dragging");
});
svg.addEventListener("pointercancel", () => { drag = null; svg.classList.remove("dragging"); });
window.addEventListener("resize", fit);
// web fonts and the side panel can change the box after first paint
if (document.fonts && document.fonts.ready) document.fonts.ready.then(fit);
new ResizeObserver(applyView).observe(svg);

// ---------- side panel ----------

let selected = null;

function select(i) {
    selected = i;
    paint();
    renderSide();
}

function fmtSlot(x, mins, isToday) {
    const title = COURSE_TITLES[x.code] || "";
    const past = isToday && mins >= x.to;
    const who = x.who.map(w => `<span class="prog-badge">${PROGRAMS[w.prog] || w.prog}${w.group === "all" ? "" : " " + w.group}</span>`).join("");
    return `<div class="slot-row${past ? " past" : ""}">
        <span class="slot-time">${t12(x.s)}–${t12(x.e)}</span>
        <span><span class="slot-course">${x.code}</span> <span class="slot-title">${title}</span>
        <span class="kind-chip">${KIND_LABEL[x.kind] || "Class"}</span><br>${who}</span></div>`;
}

function renderSide() {
    const side = document.getElementById("plan-side");
    if (selected === null) {
        side.innerHTML = `<p class="side-empty">Tap any room on the plan.</p>` + (labelling ? labelHint() : "");
        return;
    }
    const r = F.rooms[selected];
    const code = codeOf(selected);
    const { isToday, mins } = liveNow();
    let h = "";

    if (code && code !== "-") {
        h += `<h3 class="side-name">${ROOM_NAMES[code] || code}</h3><div class="side-code">${code}</div>`;
        const day = slotsFor(code, viewDay);
        const on = isToday ? day.find(s => mins >= s.from && mins < s.to) : null;
        h += `<div class="side-status">`;
        if (on) {
            h += `<span class="st-busy-course">${on.code}</span> <span class="st-busy-title">${COURSE_TITLES[on.code] || ""}</span>
                  <span class="st-when">until <b>${t12(on.e)}</b></span>`;
        } else if (isToday) {
            const next = day.find(s => mins < s.from);
            h += `<span class="st-free">free now</span>` +
                 (next ? `<span class="st-when">next: ${next.code} at <b>${t12(next.s)}</b></span>` : `<span class="st-when">nothing else today</span>`);
        } else {
            h += `<span class="st-free">${day.length} booking${day.length === 1 ? "" : "s"} on ${DAY_NAME[viewDay]}</span>`;
        }
        h += `</div>`;
        h += day.length ? day.map(s => fmtSlot(s, mins, isToday)).join("") : `<div class="slot-row">nothing scheduled</div>`;
    } else if (code === "-") {
        h += `<h3 class="side-name">Not a classroom</h3><div class="side-code">space #${selected}</div>`;
    } else {
        h += `<h3 class="side-name">Unmapped</h3><div class="side-code">space #${selected}</div>
              <p class="side-empty" style="margin-top:10px">The CAD drawing has no room numbers in it.
              Turn on <b>label rooms</b> and say which code this is.</p>`;
    }

    h += `<div class="side-meta">${r.area} m² · ${r.p.length} corners</div>`;
    if (labelling) h += labelBox(selected, code);
    side.innerHTML = h;
    wireLabelBox();
}

// ---------- label mode ----------

let labelling = false;

function labelHint() {
    return `<div class="lbl-box"><h4>label mode</h4>
        <p class="side-empty">Every unmapped space is numbered on the plan. Tap one, pick what it is.
        Progress is kept in this browser until you copy it out.</p>${labelCount()}</div>`;
}

function labelCount() {
    const done = FLOOR_CODES.filter(c => Object.values(ROOM_MAP).includes(c)).length;
    return `<div class="lbl-count">${done} of ${FLOOR_CODES.length} M4-0 codes placed</div>`;
}

function labelBox(i, code) {
    const taken = new Set(Object.entries(ROOM_MAP).filter(([k]) => +k !== i).map(([, v]) => v));
    const opts = FLOOR_CODES.map(c =>
        `<option value="${c}"${c === code ? " selected" : ""}${taken.has(c) ? " disabled" : ""}>${c} — ${ROOM_NAMES[c] || "?"}${taken.has(c) ? " (placed)" : ""}</option>`).join("");
    return `<div class="lbl-box"><h4>what is space #${i}?</h4>
        <select id="lbl-sel">
            <option value="">— pick a room code —</option>${opts}
            <option value="-"${code === "-" ? " selected" : ""}>not a classroom (corridor / service)</option>
        </select>
        <div class="lbl-actions">
            <button class="plan-btn" id="lbl-clear">clear</button>
            <button class="plan-btn" id="lbl-copy">copy mapping</button>
        </div>${labelCount()}</div>`;
}

function wireLabelBox() {
    const sel = document.getElementById("lbl-sel");
    if (!sel) return;
    sel.addEventListener("change", () => {
        if (sel.value) ROOM_MAP[selected] = sel.value; else delete ROOM_MAP[selected];
        saveMap(); paint(); renderSide();
    });
    document.getElementById("lbl-clear").addEventListener("click", () => {
        delete ROOM_MAP[selected]; saveMap(); paint(); renderSide();
    });
    document.getElementById("lbl-copy").addEventListener("click", ev => {
        const body = "const ROOM_POLY = " + JSON.stringify(ROOM_MAP, null, 4) + ";";
        navigator.clipboard.writeText(body).then(() => {
            ev.target.textContent = "copied ✓";
            setTimeout(() => { ev.target.textContent = "copy mapping"; }, 1400);
        }, () => { console.log(body); ev.target.textContent = "see console"; });
    });
}

document.getElementById("btn-label").addEventListener("click", ev => {
    labelling = !labelling;
    document.body.classList.toggle("labelling", labelling);
    ev.target.classList.toggle("on", labelling);
    paint(); renderSide();
});
document.getElementById("btn-fit").addEventListener("click", fit);

// ---------- day switcher + clock ----------

function buildDays() {
    const box = document.getElementById("plan-days");
    box.innerHTML = "";
    for (let d = 1; d <= 5; d++) {
        const b = document.createElement("button");
        b.textContent = DAY_NAME[d].slice(0, 3);
        b.className = d === viewDay ? "on" : "";
        b.addEventListener("click", () => {
            viewDay = d; buildDays(); paint(); renderSide();
        });
        box.appendChild(b);
    }
}

function tick() {
    const n = new Date();
    document.getElementById("plan-clock").textContent =
        String(n.getHours()).padStart(2, "0") + ":" + String(n.getMinutes()).padStart(2, "0");
    paint();
    if (selected !== null) renderSide();
}

viewDay = defaultDay(new Date());
buildDays();
build();
tick();
setInterval(tick, 30000);

// theme toggle — same control the other pages use
document.getElementById("theme-toggle")?.addEventListener("click", () => {
    const cur = document.documentElement.getAttribute("data-theme") === "dark" ? "light" : "dark";
    document.documentElement.setAttribute("data-theme", cur);
    try { localStorage.setItem("theme", cur); } catch (e) { }
});
