#!/usr/bin/env python3
"""Compile the mess menu into js/gen/mess.js.

Same contract as build_data.py: the JSON under data/ is the source of truth
because JSON is what other things can read, and the pages are static with no
bundler, so it is compiled into one plain synchronous script. Nobody edits the
output.

    python3 tools/build_mess.py                  compile data/mess -> js/gen
    python3 tools/build_mess.py --merge <dir>    fold per-sheet JSON into
                                                 data/mess/menu.json first
    ... --posted "10 September 2026"             when the sheets were shot
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MESS = ROOT / "data" / "mess"
GEN = ROOT / "js" / "gen" / "mess.js"
MEALS = ["breakfast", "lunch", "dinner"]
# The date the sheets were PHOTOGRAPHED, not the date they were typed up. It is
# the only date that says anything about whether the menu on screen is the menu
# on the wall. Pass --posted when you reshoot them.
POSTED = "10 September 2026"

NOTE = ("Two-week rotation, transcribed from photographs of the six sheets on "
        "the mess wall (Week-1 and Week-2 x breakfast/lunch/dinner). A course "
        "whose rule is 'Choose Any One' lists its alternatives in printed "
        "order; 'For ALL' courses have one entry. Checked by tools/"
        "check_mess.py, which requires the same courses in both weeks, seven "
        "days each, and the same number of choices on every day.")


# On the sheets, FRUIT and DESSERT sit in two labelled rows that SHARE one
# "Choose Any One" cell spanning both - so you get fruit or dessert, not one of
# each. Kept as two courses that reads as two things you get, which is wrong;
# merged, it says what the sheet says. The sheets were read one per reader and
# they split on this, which is exactly why it is settled here in one place
# rather than in six transcriptions.
PAIRED = [("FRUIT", "DESSERT")]


def normalise(courses):
    for c in courses:
        c["course"] = c["course"].upper().strip()
    out, i = [], 0
    while i < len(courses):
        a = courses[i]
        b = courses[i + 1] if i + 1 < len(courses) else None
        pair = b and (a["course"], b["course"]) in PAIRED and \
            "choose" in (a["rule"] + b["rule"]).lower()
        if pair:
            out.append({
                "course": f'{a["course"]} / {b["course"]}',
                "rule": "Choose Any One",
                "cells": {d: a["cells"][d] + b["cells"][d] for d in a["cells"]},
            })
            i += 2
        else:
            out.append(a)
            i += 1
    return out


def merge(src):
    """Fold one JSON per sheet into a single menu.json."""
    posted = (sys.argv[sys.argv.index("--posted") + 1]
              if "--posted" in sys.argv else POSTED)
    out = {"_note": NOTE, "posted_on": posted, "1": {}, "2": {}}
    seen = []
    for path in sorted(pathlib.Path(src).glob("w*.json")):
        d = json.loads(path.read_text())
        week, meal = str(d["week"]), d["meal"]
        if meal not in MEALS:
            sys.exit(f"{path.name}: unknown meal {meal!r}")
        out[week][meal] = normalise([
            {"course": c["course"], "rule": c.get("rule", ""), "cells": c["cells"]}
            for c in d["courses"]])
        seen.append(f"w{week} {meal} ({len(d['courses'])} courses)")
    missing = [f"w{w} {m}" for w in ("1", "2") for m in MEALS
               if m not in out[w]]
    if missing:
        # --partial exists so the page can be looked at while the remaining
        # sheets are still being read. It must never be how the site ships, so
        # the gap is written into the data where check_mess.py will fail on it.
        if "--partial" not in sys.argv:
            sys.exit(f"nothing read for: {', '.join(missing)}  "
                     f"(pass --partial to build anyway)")
        out["incomplete"] = missing
        print(f"  PARTIAL - still missing: {', '.join(missing)}")
    MESS.mkdir(parents=True, exist_ok=True)
    (MESS / "menu.json").write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n")
    print(f"data/mess/menu.json  <-  {', '.join(seen)}")


def strip_notes(o):
    if isinstance(o, dict):
        return {k: strip_notes(v) for k, v in o.items() if not k.startswith("_")}
    if isinstance(o, list):
        return [strip_notes(x) for x in o]
    return o


def compile_js():
    menu = strip_notes(json.loads((MESS / "menu.json").read_text()))
    service = strip_notes(json.loads((MESS / "service.json").read_text()))
    payload = {"menu": menu, "service": service}
    GEN.parent.mkdir(parents=True, exist_ok=True)
    GEN.write_text(
        "// GENERATED by tools/build_mess.py from data/mess/*.json.\n"
        "// Do not edit. Edit the JSON and re-run the tool.\n"
        "window.MESS = " + json.dumps(payload, ensure_ascii=False, indent=1)
        + ";\n")
    dishes = sum(len(v) for w in menu.values() if isinstance(w, dict)
                 for sheet in w.values() for c in sheet for v in c["cells"].values())
    print(f"js/gen/mess.js  <-  2 weeks x {len(MEALS)} meals, {dishes} dishes")


if __name__ == "__main__":
    if "--merge" in sys.argv:
        merge(sys.argv[sys.argv.index("--merge") + 1])
    compile_js()
